title: Nicolas Wolf
description: >

baseurl: "" # the subpath of your site, e.g. /blog/
# google_analytics:

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  tabs:
    output: false
